# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :joyent do |joyent|
    # base64 1.9.0
    joyent.dataset = "ff86eb8a-a069-11e3-ae0e-4f3c8983a91c"

    joyent.provision_chef = false
  end
end
